### ISSUE TITLE
python

### ISSUE THREAD

**Issue by devsecops-SRC** [southturtle/pathTraverse#1]

**Comment by kingsec666** [comment]
python 运行错误  
![image](https://user-images.githubusercontent.com/50866822/93172823-2e0fdf00-f75e-11ea-934e-17b94680b016.png)

**Comment by lakemoon602** [comment]
hello, 代码已经进行了重构，应该可以使用了~

**Comment by devsecops-SRC** [comment]
还不行啊 报错

**Comment by lakemoon602** [comment]
是在Python3环境下么？错误截图方便的话可以再贴一下，问题还是无法解决的话可以QQ联系:3467524830
